
server {
  access_log                          /var/log/nginx/access.log;
  error_log                           /var/log/nginx/error.log;
  listen                              443                                     ssl;
  server_name                         ~^bookstore\.aronim\.local$;
  ssl_certificate                     wildcard.aronim.local.crt;
  ssl_certificate_key                 wildcard.aronim.local.key;

  location ~ ^/(aronim-application-books.js) {
    proxy_pass                        http://host.docker.internal:9002;
    proxy_set_header                  Host                                    $host;
    proxy_set_header                  X-Forwarded-For                         $remote_addr;
    proxy_set_header                  X-Forwarded-Proto                       https;
    proxy_pass_request_headers        on;
  }

  location ~ ^/(aronim-application-home.js) {
    proxy_pass                        http://host.docker.internal:9003;
    proxy_set_header                  Host                                    $host;
    proxy_set_header                  X-Forwarded-For                         $remote_addr;
    proxy_set_header                  X-Forwarded-Proto                       https;
    proxy_pass_request_headers        on;
  }

  location ~ ^/(aronim-application-navbar.js) {
    proxy_pass                        http://host.docker.internal:9001;
    proxy_set_header                  Host                                    $host;
    proxy_set_header                  X-Forwarded-For                         $remote_addr;
    proxy_set_header                  X-Forwarded-Proto                       https;
    proxy_pass_request_headers        on;
  }

  location ~* ^(/) {
    proxy_pass                        http://host.docker.internal:9000;
    proxy_set_header                  Host                                    $host;
    proxy_set_header                  X-Forwarded-For                         $remote_addr;
    proxy_set_header                  X-Forwarded-Proto                       https;
    proxy_pass_request_headers        on;
  }
}
