kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001  # Mapped to PostreSQL
        hostPort: 5432
      - containerPort: 30002  # Mapped to Keycloak
        hostPort: 8080
      - containerPort: 30003  # Mapped to Keycloak
        hostPort: 9000
      - containerPort: 30004  # Mapped to Nginx
        hostPort: 80
      - containerPort: 30005  # Mapped to Nginx
        hostPort: 443
      - containerPort: 30006  # Mapped to Mailhog UI
        hostPort: 8025
      - containerPort: 30007  # Mapped to Mailhog SMTP
        hostPort: 1025
