apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  default.conf: |
    server {
      listen           80;
      listen           [::]:80;
      server_name      bookstore.aronim.local;
      root             /usr/share/nginx/html;
  
      location / {
        try_files      $uri $uri/ /index.html;
      }
  
      location = /index.html {
        index          index.html;
      }
    }
