user  nginx;

events {
}

http {
  include                               /etc/nginx/mime.types;
  include                               /etc/nginx/conf.d/*.conf;

  server {
      listen                            80                                      default_server;
      server_name                       _;
      return                            301                                     https://$host$request_uri;
  }
}
