user  nginx;

events {
}

http {
  include                               /etc/nginx/mime.types;

  server {
      listen                            80                                      default_server;
      server_name                       _;
      return                            301                                     https://$host$request_uri;
  }

  server {
    access_log                          /var/log/nginx/access.log;
    error_log                           /var/log/nginx/error.log;
    listen                              443                                     ssl;
    server_name                         ~^identity\.aronim\.local$;
    ssl_certificate                     wildcard.aronim.local.crt;
    ssl_certificate_key                 wildcard.aronim.local.key;

    location = / {
      return                            307                                     /admin/master/console/;
    }

    location ~* ^/(admin|health|js|realms|resources|robots.txt) {
      proxy_pass                        http://keycloak:8080;
      proxy_set_header                  Host                                    $host;
      proxy_set_header                  X-Forwarded-For                         $remote_addr;
      proxy_set_header                  X-Forwarded-Proto                       https;
      proxy_pass_request_headers        on;
    }
  }

  server {
    access_log                          /var/log/nginx/access.log;
    error_log                           /var/log/nginx/error.log;
    listen                              443                                     ssl;
    server_name                         ~^slack\.aronim\.local$;
    ssl_certificate                     wildcard.aronim.local.crt;
    ssl_certificate_key                 wildcard.aronim.local.key;

    location ~* ^(/) {
      proxy_pass                        http://192.168.3.162:8081;
      proxy_set_header                  Host                                    $host;
      proxy_set_header                  X-Forwarded-For                         $remote_addr;
      proxy_set_header                  X-Forwarded-Proto                       https;
      proxy_pass_request_headers        on;
    }
  }
}
