name: Acceptance Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - ".github/workflows/acceptance-tests.yml"
      - "backend/**"
      - "frontend/**"
      - "infrastructure/**"
      - "tests/acceptance/**"
  pull_request:
    branches: [ main, develop ]
    paths:
      - ".github/workflows/acceptance-tests.yml"
      - "backend/**"
      - "frontend/**"
      - "infrastructure/**"
      - "tests/acceptance/**"
  workflow_dispatch: { }

jobs:
  acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate CA Certificate
        env:
          CERTIFICATES_ARONIM_LOCAL_ROOT_CA: ${{secrets.CERTIFICATES_ARONIM_LOCAL_ROOT_CA}}
        run: |-
          echo ${CERTIFICATES_ARONIM_LOCAL_ROOT_CA} | base64 --decode > /tmp/aronim-local-root-ca.crt
          cp /tmp/aronim-local-root-ca.crt infrastructure/helm/aronim-bookstore/configmap/certificates-config/ca-certificates/
          sudo cp /tmp/aronim-local-root-ca.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
          cp ${JAVA_HOME}/lib/security/cacerts infrastructure/helm/aronim-bookstore/cacerts
          chmod 0644 infrastructure/helm/aronim-bookstore/cacerts
          keytool \
            -import \
            -noprompt \
            -alias aronim-local-root-ca \
            -file infrastructure/helm/aronim-bookstore/configmap/certificates-config/ca-certificates/aronim-local-root-ca.crt \
            -storetype JKS \
            -keystore infrastructure/helm/aronim-bookstore/cacerts \
            -storepass changeit

      - name: Build Docker image
        run: ./gradlew bootBuildImage

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.2
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Build frontend
        run: pnpm run build:development
        working-directory: ./frontend

      - name: Build frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          tags: aronim-bookstore-frontend-application:0.0.3

      - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1
        with:
          config: infrastructure/kind/kind-config.yaml
          cluster_name: kind

      - name: List Docker images
        run: docker images

      - name: Load Backend Docker iamge into KinD
        run: kind load docker-image aronim-bookstore-backend-application:0.0.1-SNAPSHOT --name kind

      - name: Load Frontend Docker iamge into KinD
        run: kind load docker-image aronim-bookstore-frontend-application:0.0.3 --name kind

      - name: Generate helm values-env.yaml
        env:
          CERTIFICATES_ARONIM_BOOKSTORE_WILDCARD_CRT: ${{ secrets.CERTIFICATES_ARONIM_BOOKSTORE_WILDCARD_CRT }}
          CERTIFICATES_ARONIM_BOOKSTORE_WILDCARD_KEY: ${{ secrets.CERTIFICATES_ARONIM_BOOKSTORE_WILDCARD_KEY }}
          CERTIFICATES_ARONIM_LOCAL_ROOT_CA: ${{ secrets.CERTIFICATES_ARONIM_LOCAL_ROOT_CA }}
          CERTIFICATES_ARONIM_WILDCARD_CRT: ${{ secrets.CERTIFICATES_ARONIM_WILDCARD_CRT }}
          CERTIFICATES_ARONIM_WILDCARD_KEY: ${{ secrets.CERTIFICATES_ARONIM_WILDCARD_KEY }}
          KEYCLOAK_BOOKSTORE_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_BOOKSTORE_ADMIN_PASSWORD }}
          KEYCLOAK_BOOKSTORE_ADMIN_USERNAME: ${{ vars.KEYCLOAK_BOOKSTORE_ADMIN_USERNAME }}
          KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_ID: ${{ vars.KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_ID }}
          KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_SECRET: ${{ secrets.KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_SECRET }}
          KEYCLOAK_BOOKSTORE_REALM_URL: ${{ vars.KEYCLOAK_BOOKSTORE_REALM_URL }}
          KEYCLOAK_HOSTNAME: ${{ vars.KEYCLOAK_HOSTNAME }}
          KEYCLOAK_MASTER_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_MASTER_ADMIN_PASSWORD }}
          KEYCLOAK_MASTER_ADMIN_USERNAME: ${{ vars.KEYCLOAK_MASTER_ADMIN_USERNAME }}
          POSTGRES_BOOKSTORE_PASSWORD: ${{ secrets.POSTGRES_BOOKSTORE_PASSWORD }}
          POSTGRES_BOOKSTORE_URL: ${{ vars.POSTGRES_BOOKSTORE_URL }}
          POSTGRES_BOOKSTORE_USERNAME: ${{ vars.POSTGRES_BOOKSTORE_USERNAME }}
          POSTGRES_KEYCLOAK_PASSWORD: ${{ secrets.POSTGRES_KEYCLOAK_PASSWORD }}
          POSTGRES_KEYCLOAK_URL: ${{ vars.POSTGRES_KEYCLOAK_URL }}
          POSTGRES_KEYCLOAK_USERNAME: ${{ vars.POSTGRES_KEYCLOAK_USERNAME }}
          POSTGRES_MULTIPLE_DATABASES: ${{ vars.POSTGRES_MULTIPLE_DATABASES }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USERNAME: ${{ vars.POSTGRES_USERNAME }}

        run: |-
          cat infrastructure/helm/aronim-bookstore/values-env.template.yaml | envsubst > infrastructure/helm/aronim-bookstore/values-env.yaml
          cat infrastructure/helm/aronim-bookstore/values-env.yaml

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: "v3.17.1"

      - name: Install aronim-bookstore Helm chart
        run: helm install aronim-bookstore infrastructure/helm/aronim-bookstore -f infrastructure/helm/aronim-bookstore/values-env.yaml --wait

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.32.2"

      - name: Checking Pods
        run: kubectl get pods

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 identity.aronim.local bookstore.aronim.local api.bookstore.aronim.local" | sudo tee -a /etc/hosts

      - name: Install Acceptance Tests dependencies
        run: pnpm install
        working-directory: ./tests/acceptance

      - name: Generate Acceptance Tests
        run: pnpm run bddgen
        working-directory: ./tests/acceptance

      - name: Run Acceptance Tests
        env:
          CI: true
          BOOKSTORE_API_URL: ${{ vars.BOOKSTORE_API_URL }}
          KEYCLOAK_BOOKSTORE_ADMIN_USERNAME: ${{ vars.KEYCLOAK_BOOKSTORE_ADMIN_USERNAME }}
          KEYCLOAK_BOOKSTORE_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_BOOKSTORE_ADMIN_PASSWORD }}
          KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_ID: ${{ vars.KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_ID }}
          KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_SECRET: ${{ secrets.KEYCLOAK_BOOKSTORE_BACKEND_CLIENT_SECRET }}
          KEYCLOAK_BOOKSTORE_REALM_URL: ${{ vars.KEYCLOAK_BOOKSTORE_REALM_URL }}
        run: pnpm run test
        working-directory: ./tests/acceptance
